set -g base-index 1
set -g pane-base-index 1
set -g mouse on
set -g status-bg black
set -g status-fg white

set-option -g status-right "%a %d %b %I:%M %p"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set-window-option -g window-status-style fg=black,bg=#a8acba,nobold
set-window-option -g window-status-current-style fg=black,bg=cyan,bright
set-window-option -g window-status-format "   #I - #W   "
set-window-option -g window-status-current-format "   #I - #W   "

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
